This toturial depends on this [website](https://www.digitalocean.com/community/tutorials/how-to-build-a-deep-learning-model-to-predict-employee-retention-using-keras-and-tensorflow)

In [207]:
import pandas as pd

df = pd.read_csv("employee.csv")
df.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [208]:
feats = ['department','salary']
df_final = pd.get_dummies(df, columns=feats, drop_first=True)
df_final.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  \
0                   3              0     1                      0   
1                   6              0     1                      0   
2                   4              0     1                      0   
3                   5              0     1                      0   
4                   3              0     1                      0   

   department_RandD  department_accounting  department_hr  \
0                 0                      0              0   
1                 0                      0              0   
2                 0                      0              0   
3                 0                      0              0   
4                 0                      0              0   

   department_management  department_marketing  department_product_mng  \
0                      0                     0                       0   
1                      0                     0                       0   
2                      0                     0                       0   
3                      0                     0                       0   
4                      0                     0                       0   

   department_sales  department_support  department_technical  salary_low  \
0                 1                   0                     0           1   
1                 1                   0                     0           0   
2                 1                   0                     0           0   
3                 1                   0                     0           1   
4                 1                   0                     0           1   

   salary_medium  
0              0  
1              1  
2              1  
3              0  
4              0

Extends more columns that rely on 'department' and 'salary'.

In [209]:
from sklearn.model_selection import train_test_split

The **sklearn** library [website](https://scikit-learn.org/stable/) <br>

In [210]:
import matplotlib.pyplot as plt 

df_without_left = df_final.drop(['left'],axis=1)
df_with_left = df_final['left']

X = df_without_left.values
y = df_with_left.values

df_without_left.head()
# df_with_left.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  promotion_last_5years  department_RandD  \
0                   3              0                      0                 0   
1                   6              0                      0                 0   
2                   4              0                      0                 0   
3                   5              0                      0                 0   
4                   3              0                      0                 0   

   department_accounting  department_hr  department_management  \
0                      0              0                      0   
1                      0              0                      0   
2                      0              0                      0   
3                      0              0                      0   
4                      0              0                      0   

   department_marketing  department_product_mng  department_sales  \
0                     0                       0                 1   
1                     0                       0                 1   
2                     0                       0                 1   
3                     0                       0                 1   
4                     0                       0                 1   

   department_support  department_technical  salary_low  salary_medium  
0                   0                     0           1              0  
1                   0                     0           0              1  
2                   0                     0           0              1  
3                   0                     0           1              0  
4                   0                     0           1              0

Drop the **left** in the **X** value to avoid distortion in the chart. and the **y** value only in axis y.

In [211]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

Use the **sklearn** library to **split** the **data** (keras expects it to be **numpy** arrays) and distribute the **X** and **y** with **train** and **test** types.

The document for module [tran_test_splite](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) <br>
**test_size**: float or int, default=None, should be between 0.0 and 1.0 

In [212]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

print("train %s \ntest %s" % (X_train.min(axis=0), X_test.min(axis=0)))

train [-2.11188608 -2.07818196 -1.45860171 -2.09827515 -1.02366313 -0.40906452
 -0.149325   -0.2362468  -0.2362468  -0.22642139 -0.20889751 -0.23915402
 -0.25351058 -0.61334826 -0.41649246 -0.47413256 -0.97376993 -0.86693997] 
test [-2.11188608 -2.07818196 -1.45860171 -2.07828706 -1.02366313 -0.40906452
 -0.149325   -0.2362468  -0.2362468  -0.22642139 -0.20889751 -0.23915402
 -0.25351058 -0.61334826 -0.41649246 -0.47413256 -0.97376993 -0.86693997]


x′=x−μσ

This will transform the values to have a mean of 0 and a standard deviation of 1. <br>
This step is important because you’re comparing features that have different measurements

In [213]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [214]:
classifier = Sequential()

You’ve used **Sequential** to initialize the classifier.

In [215]:
classifier.add(Dense(9, kernel_initializer="uniform", activation="relu", input_dim=18))

Now, Add the first layer into the network. <br>

The layer of function [website](https://keras.io/api/layers/activations/)
The first number of nodes that your network should have. <br>
**kernel_initializer**: it's the function that initializes the weights. <br>
**activation**: There're usually linear and non-linear activation functions. <br>
**input_dim**: it was represents the number of features in your dataset.

In [216]:
classifier.add(Dense(1, kernel_initializer="uniform", activation="sigmoid"))

This is output layer.

The number of output nodes. You expect to get one output: if an employee leaves the company. Therefore you specify one output node. <br>
**sigmoid**: Applies the sigmoid activation function. <br> 
+ For small values (<-5), sigmoid returns a value close to zero, and for large values (>5) the result of the function gets close to 1.

In [217]:
classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

It will appy a gradient descent to the neural network. <br>

**optimizer**: it's the gradient descent. <br>
**loss**: this is a binary classification problem you use the binary_crossentropy loss function. <br>
**accuracy**: evaluate your model base on accuracy.


In [218]:
classifier.fit(X_train, y_train, batch_size=10, epochs=1)

1050/1050 [==============================] - 5s 3ms/step - loss: 0.4229 - accuracy: 0.8233


Begin training the model with the layers. <br>

**batch_size**: it was represents the number of samples that will go through the neural network at each training round. <br>
**epochs**: Use to control the number of times on training. <br>
**loss**: If this value gradually falls below the previous value, the result will be even better than before.

In [219]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

141/141 [==============================] - 0s 2ms/step


array([[ True],
       [False],
       [False],
       ...,
       [ True],
       [ True],
       [False]])

You try predict result with test dataset.

In [220]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[3234,  193],
       [ 293,  780]], dtype=int64)

The confusion matrix output means that your deep learning model made 3283 + 119 correct predictions and 668 + 430 wrong predictions. You can calculate the accuracy with: (3283 + 119) / 4500. The total number of observations in your dataset is 4500. This gives you an accuracy of 81.7%. This is a very good accuracy rate since you can achieve at least 81% correct predictions from your model.

In [221]:
import numpy as np
new_pred = classifier.predict(sc.transform(np.array([[0.26,0.7 ,3., 238., 6., 0.,0.,0.,0., 0.,0.,0.,0.,0.,1.,0., 0.,1.]])))


1/1 [==============================] - 0s 32ms/step


array([[False]])

Pass a employee to predict the result who will be retention.

In [ ]:
# try to testing test the result.
new_pred = (new_pred > 0.5)
new_pred

Try threshold 50%

In [222]:
new_pred = (new_pred > 0.6)
new_pred

array([[False]])

Try threshold 60% <br><br>
Now, you'll see the accuracy not very well. <br>
Next we'll work to improve the accuracy

In [223]:
#from scikeras.wrappers import KerasClassifier, KerasRegressor
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [224]:
def make_classifier():
    classifier = Sequential()
    classifier.add(Dense(9, kernel_initializer="uniform", activation="relu", input_dim=18))
    classifier.add(Dense(1, kernel_initializer="uniform", activation="sigmoid"))
    classifier.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])
    return classifier

In [225]:
classifier = KerasClassifier(build_fn=make_classifier, batch_size=10, nb_epoch=1)

C:\Users\85291\AppData\Local\Temp\ipykernel_13772\607920770.py:1: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  classifier = KerasClassifier(build_fn=make_classifier, batch_size=10, nb_epoch=1)


In [226]:
accuracies = cross_val_score(estimator=classifier, X=X_train, y=y_train, cv=10, n_jobs=-1)

In [227]:
mean = accuracies.mean()
mean

0.8255071043968201

In [228]:
variance = accuracies.var()
variance

0.001689787359485706

The **accuracies.var()** to see your model whether is accurate result. <br>
The variance is very low is means that your model is performing very well.