In [3]:
import numpy as np

a = np.arange(24)
# b = a.reshape(3, 5) it's wrong since 3x5 != 24
b = a.reshape(3,8)

print(b)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
